#!/bin/bash
# Generate docker-compose.multi-tenant.yml from the tenants/ directory.
#
# Usage:
#   ./scripts/generate-compose.sh
#
# Scans tenants/ for subdirectories containing config.json,
# then writes docker-compose.multi-tenant.yml in the project root.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR/.."
TENANTS_DIR="$PROJECT_DIR/tenants"
OUTPUT="$PROJECT_DIR/docker-compose.multi-tenant.yml"

if [ ! -d "$TENANTS_DIR" ]; then
  echo "Error: tenants/ directory not found at $TENANTS_DIR"
  exit 1
fi

TENANTS=()
for dir in "$TENANTS_DIR"/*/; do
  name="$(basename "$dir")"
  if [ -f "$dir/config.json" ]; then
    TENANTS+=("$name")
  fi
done

if [ ${#TENANTS[@]} -eq 0 ]; then
  echo "Error: No tenants found in $TENANTS_DIR"
  echo "Run ./scripts/add-tenant.sh first."
  exit 1
fi

cat > "$OUTPUT" << 'HEADER'
# ZeptoClaw Multi-Tenant Deployment
# Auto-generated by scripts/generate-compose.sh — do not edit manually.
# To add a tenant: ./scripts/add-tenant.sh <name> <token> <key>
# To rebuild:      ./scripts/generate-compose.sh

x-zeptoclaw-defaults: &defaults
  image: ghcr.io/qhkm/zeptoclaw:latest
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "3"
  deploy:
    resources:
      limits:
        memory: 128M
        cpus: "0.25"
      reservations:
        memory: 32M
        cpus: "0.05"

services:
HEADER

for TENANT in "${TENANTS[@]}"; do
  cat >> "$OUTPUT" << TENANT_BLOCK

  # =========================================================
  # Tenant: $TENANT
  # =========================================================
  tenant-$TENANT:
    <<: *defaults
    container_name: zc-$TENANT
    volumes:
      - $TENANT-data:/data
      - ./tenants/$TENANT/config.json:/data/.zeptoclaw/config.json
    environment:
      - RUST_LOG=zeptoclaw=info
      - RUST_LOG_FORMAT=json
      - ZEPTOCLAW_HEALTH_PORT=9090
    labels:
      com.zeptoclaw.tenant: "$TENANT"
      com.zeptoclaw.version: "latest"
      com.zeptoclaw.env: production
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:9090/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    command: ["zeptoclaw", "gateway"]
TENANT_BLOCK
done

echo "" >> "$OUTPUT"
echo "volumes:" >> "$OUTPUT"
for TENANT in "${TENANTS[@]}"; do
  echo "  $TENANT-data:" >> "$OUTPUT"
done

echo "✓ Generated $OUTPUT"
echo "  Tenants: ${TENANTS[*]}"
echo ""
echo "To deploy:"
echo "  docker compose -f docker-compose.multi-tenant.yml up -d"
